"""Add refresh_tokens table

Revision ID: 2e0f5a0c5b6e
Revises: 66cc011f61af
Create Date: 2026-02-07 07:54:56.208692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0f5a0c5b6e'
down_revision: Union[str, Sequence[str], None] = '66cc011f61af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
